version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      patch-and-minor-updates:
        applies-to: "version-updates"
        update-types:
          - "patch"
          - "minor"
    # Keep ignores in line with their respective npm-check-updates configs:
    # - "version-update:semver-patch" -> .ncurc.patch.cjs
    # - "version-update:semver-minor" -> .ncurc.minor.cjs
    # - "version-update:semver-major" -> .ncurc.major.cjs
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      # the following 5 ignored dependencies should be removed when we update to Storybook 9
      - dependency-name: "@storybook/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "storybook"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@etchteam/storybook-addon-status"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@whitespace/storybook-addon-html"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-major"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
