packages:
  - packages/*
  - packages/components-react/*
  - packages/components-css/*
  - packages/docs/*
  - packages/tokens/*

autoInstallPeers: false

engineStrict: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild

saveExact: true

savePrefix: ''
