autoInstallPeers: false
engineStrict: true
onlyBuiltDependencies:
  - esbuild
saveExact: true
savePrefix: ""
packages:
  - packages/*
  - packages/components-react/*
  - packages/components-css/*
  - packages/docs/*
  - packages/tokens/*
