name: 🐛 Rapporteer een bug
description: Iets werkt niet naar behoren
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Allereerst bedankt voor je bijdrage!

        Vul het onderstaande formulier in om een GitHub issue aan te maken.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Bekijk de [huidige Candidate componenten](https://github.com/nl-design-system/candidate/tree/main/packages/components-react/)
      options:
        - Code
        - Code Block
        - Color Sample
        - Data Badge
        - Heading
        - Link
        - Mark
        - Number Badge
        - Paragraph
        - Skip Link
        - Anders...
    validations:
      required: true

  - type: textarea
    id: reproductie
    attributes:
      label: Reproductie
      description: Link naar een reproductie en de stappen om het gedrag te reproduceren.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Verwacht gedrag
      description: Een beknopte beschrijving van wat je had verwacht.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Werkelijk gedrag
      description: Een beknopte beschrijving van wat je had verwacht.
    validations:
      required: true
