name: 📚 Documentatie Issue
description: Er ontbreekt iets, of er is iets mis met de documentatie
title: "[docs]: "
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        Allereerst bedankt voor je bijdrage!

        Voor documenatie updates mogen pull requests naar de `main` branch gemaakt worden.

        Als je geen pull request maakt kun je in dit issue aangeven wat er niet correct is of wat je mist in de documentatie.

  - type: textarea
    attributes:
      label: Beschrijf wat er niet correct is of ontbreekt in de documentatie
      description: Een beknopte beschrijving van wat je in de documentatie dacht te kunnen vinden
    validations:
      required: true
