name: Accessibility-alt-text-bot
on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - edited

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  accessibility_alt_text_bot:
    name: Check for alt texts to be set
    runs-on: ubuntu-latest
    steps:
      - name: Run alt-text checks
        uses: github/accessibility-alt-text-bot@531a7430c6930a39cae5a0aab2d165284468060f # v1.7.1
