name: Changeset status

on: pull_request

jobs:
  changeset-status:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.head_ref, 'changeset-release/') }}
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # 1.12.0
        with:
          app-id: ${{ vars.NL_DESIGN_SYSTEM_BOT_APP_ID }}
          private-key: ${{ secrets.NL_DESIGN_SYSTEM_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        if: ${{ github.actor == 'dependabot[bot]' }}

      - name: Changeset status
        id: changeset-status
        run: |
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            if [[ "${{ steps.dependabot-metadata.outputs.update-type }}" == "version-update:semver-patch" ]] || [[ "${{ steps.dependabot-metadata.outputs.update-type }}" == "version-update:semver-minor" ]]; then
              echo "status=0" | tee -a $GITHUB_OUTPUT
              exit 0
            fi
          fi

          if pnpm run changeset:status; then
            echo "status=0" | tee -a $GITHUB_OUTPUT
          else
            echo "status=1" | tee -a $GITHUB_OUTPUT
          fi

      - name: Find existing comment
        id: find-existing-comment
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          COMMENT=$(gh api repos/:owner/:repo/issues/${{ github.event.pull_request.number }}/comments --jq ".[] | select(.user.login == \"${{ steps.app-token.outputs.app-slug }}[bot]\") | .id")
          echo "comment=${COMMENT}" | tee -a $GITHUB_OUTPUT

      - name: Remove existing comment
        if: ${{ steps.find-existing-comment.outputs.comment != '' && steps.changeset-status.outputs.status == 0 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api --method DELETE repos/:owner/:repo/issues/comments/${{ steps.find-existing-comment.outputs.comment }}
          exit 0

      - name: Create new comment
        if: ${{ steps.find-existing-comment.outputs.comment == '' && steps.changeset-status.outputs.status == 1 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body ":warning: Deze pull request mist een changeset terwijl er wel een nodig is :warning:"
          exit 1

      - name: Update existing comment
        if: ${{ steps.find-existing-comment.outputs.comment != '' && steps.changeset-status.outputs.status == 1 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --edit-last --body ":warning: Deze pull request mist nog steeds een changeset terwijl er wel een nodig is. :warning:"
          exit 1
