name: Changeset status

on:
  workflow_run:
    workflows:
      # Triggered by the Continuous Integration workflow
      - Continuous Integration
    types:
      # Start running parallel to the Continuous Integration workflow
      - in_progress

permissions:
  # Read the contents of the repo
  contents: read
  # Write the result back to the pull request that triggered this workflow
  checks: write
  # Be able to comment on the pull request
  pull-requests: write

jobs:
  changeset-status:
    runs-on: ubuntu-latest
    # Do _NOT_ run this job if:
    #
    # 1. the branch was created by the Changeset Action itself
    # 2. the branch was created by Dependabot because it cannot (and should not) access the `private-key` secret
    if: ${{ !startsWith(github.event.workflow_run.head_branch, 'changeset-release/') && github.actor != 'dependabot[bot]' }}
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # 2.0.6
        with:
          app-id: ${{ vars.NL_DESIGN_SYSTEM_BOT_APP_ID }}
          private-key: ${{ secrets.NL_DESIGN_SYSTEM_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          # Fetch all history for all branches so that `changeset:status` in package.json#scripts can determine if
          # a changeset is needed or not.
          fetch-depth: 0

      - name: Start check
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api --method POST repos/:owner/:repo/check-runs \
            --header "Accept: application/vnd.github+json" \
            --field head_sha=${{ github.event.workflow_run.head_sha }} \
            --field name="${{ github.workflow }}" \

      - name: Install pnpm package manager
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Changset status
        id: changeset-status
        run: |
          if pnpm run changeset:status; then
            echo "status=0" | tee -a $GITHUB_OUTPUT
          else
            echo "status=1" | tee -a $GITHUB_OUTPUT
          fi

      - name: Find existing comment
        id: find-existing-comment
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          COMMENT=$(gh api repos/:owner/:repo/issues/${{ github.event.pull_request.number }}/comments --jq ".[] | select(.user.login == \"${{ steps.app-token.outputs.app-slug }}[bot]\") | .id")
          echo "comment=${COMMENT}" | tee -a $GITHUB_OUTPUT

      - name: Remove existing comment
        if: ${{ steps.find-existing-comment.outputs.comment != '' && steps.changeset-status.outputs.status == 0 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh api --method DELETE repos/:owner/:repo/issues/comments/${{ steps.find-existing-comment.outputs.comment }}
          gh api --method POST repos/:owner/:repo/check-runs \
            --header "Accept: application/vnd.github+json" \
            --field head_sha=${{ github.event.workflow_run.head_sha }} \
            --field name="${{ github.workflow }}" \
            --field conclusion="success"
          exit 0

      - name: Create new comment
        if: ${{ steps.find-existing-comment.outputs.comment == '' && steps.changeset-status.outputs.status == 1 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} \
            --body ":warning: Deze pull request mist een changeset terwijl er wel een nodig is :warning:"
          gh api --method POST repos/:owner/:repo/check-runs \
            --header "Accept: application/vnd.github+json" \
            --field head_sha=${{ github.event.workflow_run.head_sha }} \
            --field name="${{ github.workflow }}" \
            --field conclusion="failure"
          exit 1

      - name: Update existing comment
        if: ${{ steps.find-existing-comment.outputs.comment != '' && steps.changeset-status.outputs.status == 1 }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} \
            --edit-last \
            --body ":warning: Deze pull request mist nog steeds een changeset terwijl er wel een nodig is. :warning:"
          gh api --method POST repos/:owner/:repo/check-runs \
            --header "Accept: application/vnd.github+json" \
            --field head_sha=${{ github.event.workflow_run.head_sha }} \
            --field name="${{ github.workflow }}" \
            --field conclusion="failure"
          exit 1
