on: pull_request

name: Pull Request

permissions:
  pull-requests: read

jobs:
  check-changeset:
    name: Check changeset
    runs-on: ubuntu-latest

    outputs:
      skip_changeset: ${{ steps.check-public-changes.outputs.skip_changeset }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if public packages changed
        id: check-public-changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD)

          PUBLIC_CHANGED=0
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" == packages/public-package-1/* || "$FILE" == packages/public-package-2/* ]]; then
              echo "Public package changed: $FILE"
              PUBLIC_CHANGED=1
              break
            fi
          done

          if [[ "$PUBLIC_CHANGED" -eq 0 ]]; then
            echo "skip_changeset=true" >> $GITHUB_ENV
            echo "::set-output name=skip_changeset::true"
          else
            echo "::set-output name=skip_changeset::false"
          fi

  changeset-bot:
    needs: check-changeset
    runs-on: ubuntu-latest
    if: needs.check-changeset.outputs.skip_changeset != 'true'
    name: Summon changeset bot
    steps:
      - name: Run Changeset Action
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
